### ISSUE TITLE
Jamtaba does not compile on ubuntu 20.04: libx264 related issues

### ISSUE THREAD

**Issue by pedrorolo** [elieserdejesus/JamTaba#1397]
The errors are all similar to this. Google about this tells me it might be something related with libc changes. Any sugested workaround?
```
/usr/bin/ld: /home/pedro/workspace/JamTaba/PROJECTS/Standalone/../../libs/static/linux64/libx264.a(analyse-8.o): in function `x264_8_analyse_init_costs':
analyse.c:(.text+0x227d5): undefined reference to `__log2f_finite'
/usr/bin/ld: /home/pedro/workspace/JamTaba/PROJECTS/Standalone/../../libs/static/linux64/libx264.a(ratecontrol-8.o): in function `predict_row_size_to_end':
ratecontrol.c:(.text+0x29): undefined reference to `__powf_finite'
/usr/bin/ld: /home/pedro/workspace/JamTaba/PROJECTS/Standalone/../../libs/static/linux64/libx264.a(ratecontrol-8.o): in function `x264_8_adaptive_quant_frame':
ratecontrol.c:(.text+0xcee): undefined reference to `__powf_finite'
/usr/bin/ld: /home/pedro/workspace/JamTaba/PROJECTS/Standalone/../../libs/static/linux64/libx264.a(ratecontrol-8.o): in function `qscale2bits':
ratecontrol.c:(.text+0xed6): undefined reference to `__pow_finite'
/usr/bin/ld: /home/pedro/workspace/JamTaba/PROJECTS/Standalone/../../libs/static/linux64/libx264.a(ratecontrol-8.o): in function `get_qscale':
ratecontrol.c:(.text+0x1020): undefined reference to `__pow_finite'
/usr/bin/ld: ratecontrol.c:(.text+0x10be): undefined reference to `__powf_finite'
/usr/bin/ld: /home/pedro/workspace/JamTaba/PROJECTS/Standalone/../../libs/static/linux64/libx264.a(ratecontrol-8.o): in function `clip_qscale':
ratecontrol.c:(.text+0x119d): undefined reference to `__powf_finite'
/usr/bin/ld: ratecontrol.c:(.text+0x150c): undefined reference to `__log_finite'
/usr/bin/ld: ratecontrol.c:(.text+0x1523): undefined reference to `__log_finite'
/usr/bin/ld: ratecontrol.c:(.text+0x153a): undefined reference to `__log_finite'
/usr/bin/ld: ratecontrol.c:(.text+0x156d): undefined reference to `__exp_finite'
/usr/bin/ld: /home/pedro/workspace/JamTaba/PROJECTS/Standalone/../../libs/static/linux64/libx264.a(ratecontrol-8.o): in function `rate_estimate_qscale':
ratecontrol.c:(.text+0x1c03): undefined reference to `__pow_finite'
/usr/bin/ld: ratecontrol.c:(.text+0x1c31): undefined reference to `__log2f_finite'
/usr/bin/ld: ratecontrol.c:(.text+0x1dea): undefined reference to `__pow_finite'
/usr/bin/ld: ratecontrol.c:(.text+0x1f11): undefined reference to `__pow_finite'
/usr/bin/ld: ratecontrol.c:(.text+0x2030): undefined reference to `__pow_finite'
/usr/bin/ld: ratecontrol.c:(.text+0x2170): undefined reference to `__powf_finite'
/usr/bin/ld: ratecontrol.c:(.text+0x21c3): undefined reference to `__pow_finite'
/usr/bin/ld: ratecontrol.c:(.text+0x258e): undefined reference to `__log2f_finite'
/usr/bin/ld: ratecontrol.c:(.text+0x27ce): undefined reference to `__powf_finite'
/usr/bin/ld: ratecontrol.c:(.text+0x287c): undefined reference to `__powf_finite'
/usr/bin/ld: /home/pedro/workspace/JamTaba/PROJECTS/Standalone/../../libs/static/linux64/libx264.a(ratecontrol-8.o): in function `x264_8_ratecontrol_init_reconfigurable':
ratecontrol.c:(.text+0x3702): undefined reference to `__pow_finite'
/usr/bin/ld: ratecontrol.c:(.text+0x3742): undefined reference to `__powf_finite'
/usr/bin/ld: /home/pedro/workspace/JamTaba/PROJECTS/Standalone/../../libs/static/linux64/libx264.a(ratecontrol-8.o): in function `x264_8_ratecontrol_new':
ratecontrol.c:(.text+0x3a4e): undefined reference to `__pow_finite'
/usr/bin/ld: ratecontrol.c:(.text+0x3aa0): undefined reference to `__log2f_finite'
/usr/bin/ld: ratecontrol.c:(.text+0x3acc): undefined reference to `__log2f_finite'
/usr/bin/ld: ratecontrol.c:(.text+0x3b6d): undefined reference to `__pow_finite'
/usr/bin/ld: ratecontrol.c:(.text+0x3c0b): undefined reference to `__powf_finite'
/usr/bin/ld: ratecontrol.c:(.text+0x3c38): undefined reference to `__powf_finite'
/usr/bin/ld: ratecontrol.c:(.text+0x4064): undefined reference to `__powf_finite'
/usr/bin/ld: ratecontrol.c:(.text+0x4605): undefined reference to `__log2f_finite'
/usr/bin/ld: ratecontrol.c:(.text+0x4aee): undefined reference to `__powf_finite'
/usr/bin/ld: ratecontrol.c:(.text+0x51a8): undefined reference to `__powf_finite'
/usr/bin/ld: ratecontrol.c:(.text+0x528a): undefined reference to `__log2_finite'
/usr/bin/ld: ratecontrol.c:(.text+0x52a2): undefined reference to `__log2_finite'
/usr/bin/ld: ratecontrol.c:(.text+0x52b7): undefined reference to `__log2_finite'
/usr/bin/ld: ratecontrol.c:(.text+0x5fb9): undefined reference to `__exp_finite'
/usr/bin/ld: ratecontrol.c:(.text+0x61d2): undefined reference to `__exp_finite'
/usr/bin/ld: ratecontrol.c:(.text+0x6595): undefined reference to `__pow_finite'
/usr/bin/ld: ratecontrol.c:(.text+0x6789): undefined reference to `__log2f_finite'
/usr/bin/ld: ratecontrol.c:(.text+0x6b28): undefined reference to `__exp_finite'
/usr/bin/ld: ratecontrol.c:(.text+0x6dca): undefined reference to `__exp_finite'
/usr/bin/ld: ratecontrol.c:(.text+0x6dfa): undefined reference to `__powf_finite'
/usr/bin/ld: ratecontrol.c:(.text+0x6e6f): undefined reference to `__powf_finite'
/usr/bin/ld: ratecontrol.c:(.text+0x7177): undefined reference to `__exp_finite'
/usr/bin/ld: ratecontrol.c:(.text+0x72e3): undefined reference to `__powf_finite'
/usr/bin/ld: ratecontrol.c:(.text+0x731e): undefined reference to `__powf_finite'
/usr/bin/ld: /home/pedro/workspace/JamTaba/PROJECTS/Standalone/../../libs/static/linux64/libx264.a(ratecontrol-8.o): in function `x264_8_ratecontrol_summary':
ratecontrol.c:(.text+0x77df): undefined reference to `__pow_finite'
/usr/bin/ld: ratecontrol.c:(.text+0x7804): undefined reference to `__log2f_finite'
/usr/bin/ld: /home/pedro/workspace/JamTaba/PROJECTS/Standalone/../../libs/static/linux64/libx264.a(ratecontrol-8.o): in function `x264_8_ratecontrol_start':
ratecontrol.c:(.text+0x8051): undefined reference to `__log2f_finite'
/usr/bin/ld: ratecontrol.c:(.text+0x80ad): undefined reference to `__log2f_finite'
/usr/bin/ld: /home/pedro/workspace/JamTaba/PROJECTS/Standalone/../../libs/static/linux64/libx264.a(ratecontrol-8.o): in function `x264_8_ratecontrol_mb':
ratecontrol.c:(.text+0x8288): undefined reference to `__powf_finite'
/usr/bin/ld: /home/pedro/workspace/JamTaba/PROJECTS/Standalone/../../libs/static/linux64/libx264.a(ratecontrol-8.o): in function `x264_8_ratecontrol_slice_type':
ratecontrol.c:(.text+0x8e24): undefined reference to `__log2f_finite'
/usr/bin/ld: ratecontrol.c:(.text+0x8e80): undefined reference to `__log2f_finite'
/usr/bin/ld: ratecontrol.c:(.text+0x8fd9): undefined reference to `__powf_finite'
/usr/bin/ld: ratecontrol.c:(.text+0x9030): undefined reference to `__powf_finite'
/usr/bin/ld: /home/pedro/workspace/JamTaba/PROJECTS/Standalone/../../libs/static/linux64/libx264.a(ratecontrol-8.o): in function `x264_8_ratecontrol_end':
ratecontrol.c:(.text+0x94fd): undefined reference to `__powf_finite'
/usr/bin/ld: ratecontrol.c:(.text+0x9593): undefined reference to `__powf_finite'
/usr/bin/ld: ratecontrol.c:(.text+0x95d1): undefined reference to `__pow_finite'
/usr/bin/ld: ratecontrol.c:(.text+0x96c2): undefined reference to `__powf_finite'
/usr/bin/ld: ratecontrol.c:(.text+0x9c0e): undefined reference to `__powf_finite'
/usr/bin/ld: ratecontrol.c:(.text+0x9ce1): undefined reference to `__powf_finite'
/usr/bin/ld: /home/pedro/workspace/JamTaba/PROJECTS/Standalone/../../libs/static/linux64/libx264.a(ratecontrol-8.o): in function `x264_8_threads_distribute_ratecontrol':
ratecontrol.c:(.text+0xa054): undefined reference to `__powf_finite'
/usr/bin/ld: /home/pedro/workspace/JamTaba/PROJECTS/Standalone/../../libs/static/linux64/libx264.a(ratecontrol-8.o): in function `x264_8_threads_merge_ratecontrol':
ratecontrol.c:(.text+0xa653): undefined reference to `__powf_finite'
/usr/bin/ld: /home/pedro/workspace/JamTaba/PROJECTS/Standalone/../../libs/static/linux64/libx264.a(ratecontrol-8.o): in function `clip_qscale':
ratecontrol.c:(.text+0x159d): undefined reference to `__exp_finite'
/usr/bin/ld: /home/pedro/workspace/JamTaba/PROJECTS/Standalone/../../libs/static/linux64/libx264.a(analyse-10.o): in function `x264_10_analyse_init_costs':
analyse.c:(.text+0x22a55): undefined reference to `__log2f_finite'
/usr/bin/ld: /home/pedro/workspace/JamTaba/PROJECTS/Standalone/../../libs/static/linux64/libx264.a(ratecontrol-10.o): in function `predict_row_size_to_end':
ratecontrol.c:(.text+0x29): undefined reference to `__powf_finite'
/usr/bin/ld: /home/pedro/workspace/JamTaba/PROJECTS/Standalone/../../libs/static/linux64/libx264.a(ratecontrol-10.o): in function `x264_10_adaptive_quant_frame':
ratecontrol.c:(.text+0xcfe): undefined reference to `__powf_finite'
/usr/bin/ld: /home/pedro/workspace/JamTaba/PROJECTS/Standalone/../../libs/static/linux64/libx264.a(ratecontrol-10.o): in function `qscale2bits':
```
